"""Bake the default layout into data/map.js: room positions, connection ends and bends.

    python3 tools/bake_layout.py              # bake tools/default_layout.json into a fresh data/map.js (run_all.sh does this)
    python3 tools/bake_layout.py layout.js    # make a layout from edit mode (data/layout.js, or Map → Layout → Export…)
                                              # the new default: folds it into tools/default_layout.json and
                                              # data/map.js, no regeneration needed

tools/default_layout.json holds the default as offsets from the generated positions, so regenerating reproduces
it. The result is tagged with `layoutBase`; the app ignores saved layouts made against a different base.
Markers are stored relative to their room's default position, so map.js also says how far each room has moved
since the generated positions (`bakedShift`) and since each earlier default (`baseShifts`): the app shifts
saved markers once, and nothing jumps.
"""
import hashlib
import json
import os
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.environ.get("LONGING_OUT", os.path.abspath(os.path.join(TOOLS, "..")))
DEFAULT = os.path.join(TOOLS, "default_layout.json")
MAP_JS = os.path.join(ROOT, "data", "map.js")
LAYOUT_JS = os.path.join(ROOT, "data", "layout.js")
GREAT_CAVE = 67


def load_js(path):
    s = open(path, encoding="utf-8").read()
    if "{" not in s:
        sys.exit(f"{path} holds no layout")
    return json.loads(s[s.index("{"):s.rindex("}") + 1])


def base_id(layout):
    return hashlib.sha1(json.dumps(layout, sort_keys=True).encode()).hexdigest()[:12]


def link_keys(links):
    """(key, link) pairs, keyed as the app keys them."""
    seen = {}
    for l in links:
        base = f"{min(l['a'], l['b'])}-{max(l['a'], l['b'])}-{l['kind']}"
        n = seen[base] = seen.get(base, -1) + 1
        yield (f"{base}#{n}" if n else base), l


def add(p, q):
    return [round(p[0] + q[0], 2), round(p[1] + q[1], 2)]


def write_map(data, layout):
    rooms = layout["rooms"]
    since = lambda old: {k: v for k in rooms.keys() | old.keys()
                         if (v := add(rooms.get(k, [0, 0]), [-x for x in old.get(k, [0, 0])])) != [0, 0]}
    data["layoutBase"] = base_id(layout)
    data["bakedShift"] = rooms
    data["baseShifts"] = {b: since(old) for b, old in layout.get("bases", {}).items()}
    with open(MAP_JS, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/export.py from the game's data files; default layout baked in by tools/bake_layout.py.\n")
        f.write("window.LONGING_MAP = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"baked {len(rooms)} room moves, {len(layout['bends'])} bends, "
          f"{len(layout.get('ends', {}))} moved ends into data/map.js (base {data['layoutBase']})")


def bake():
    """Bake tools/default_layout.json into data/map.js fresh from export.py."""
    layout = json.load(open(DEFAULT))
    data = load_js(MAP_JS)
    if data.get("layoutBase"):
        sys.exit("data/map.js is already baked; re-run export.py first")
    rooms = {r["id"]: r for r in data["rooms"]}
    off = lambda rid: layout["rooms"].get(str(rooms[rid]["sharedWith"] or rid), [0, 0])

    for r in data["rooms"]:
        dx, dy = off(r["id"])
        r["rect"][0] = round(r["rect"][0] + dx, 3)
        r["rect"][1] = round(r["rect"][1] + dy, 3)

    # the dark climbs start where their waypoint chain leaves the Great Cave (as the app does)
    path_start = {p["to"]: p["pts"][0] for p in data["paths"]}
    for key, l in link_keys(data["links"]):
        ends = layout.get("ends", {}).get(key, {})
        for side, rid in (("a", l["a"]), ("b", l["b"])):
            pt = l["p" + side]
            if l["kind"] == "dark" and rid == GREAT_CAVE:
                pt = path_start[l["b"] if side == "a" else l["a"]]
            l["p" + side] = add(ends.get(side, pt), off(rid))
        if key in layout["bends"]:
            l["bends"] = layout["bends"][key]
    if any(l["kind"] == "dark" and "bends" not in l for l in data["links"]):
        sys.exit("a dark climb has no bends in the layout; bend it in edit mode before baking")
    data["paths"] = []          # their routes now live in the links' bends
    write_map(data, layout)


def merge(path):
    """Fold a layout made in edit mode against the current default into it, and into data/map.js."""
    new = load_js(path)
    old = json.load(open(DEFAULT))
    data = load_js(MAP_JS)
    if data.get("layoutBase") != base_id(old):
        sys.exit("data/map.js isn't baked from tools/default_layout.json; run run_all.sh first")
    if new.get("base") != data["layoutBase"]:
        sys.exit(f"{path} was made against a different default layout")
    rooms = {r["id"]: r for r in data["rooms"]}
    primary = lambda rid: str(rooms[rid]["sharedWith"] or rid)
    move = lambda rid: new["rooms"].get(primary(rid), [0, 0])

    # map.js already holds the current default, which is the frame edit mode works in
    for r in data["rooms"]:
        dx, dy = move(r["id"])
        r["rect"][0] = round(r["rect"][0] + dx, 3)
        r["rect"][1] = round(r["rect"][1] + dy, 3)
    ends = {k: dict(v) for k, v in old.get("ends", {}).items()}
    for key, l in link_keys(data["links"]):
        e = new.get("ends", {}).get(key, {})
        for side, rid in (("a", l["a"]), ("b", l["b"])):
            l["p" + side] = add(e.get(side, l["p" + side]), move(rid))
            if side in e:   # default_layout.json keeps ends in the generated frame
                ends.setdefault(key, {})[side] = add(e[side], [-x for x in old["rooms"].get(primary(rid), [0, 0])])
        if key in new["bends"]:
            l["bends"] = new["bends"][key]

    moved = dict(old["rooms"])
    for k, d in new["rooms"].items():
        v = add(moved.get(k, [0, 0]), d)
        if v == [0, 0]:
            moved.pop(k, None)
        else:
            moved[k] = v
    layout = {"version": 1, "updated": max(old.get("updated", 0), new.get("updated", 0)), "rooms": moved,
              "bends": {**old["bends"], **new["bends"]}, "ends": ends,
              "bases": {**old.get("bases", {}), data["layoutBase"]: old["rooms"]}}   # earlier defaults, for markers
    with open(DEFAULT, "w", encoding="utf-8") as f:
        json.dump(layout, f, indent=1)
        f.write("\n")
    write_map(data, layout)
    if os.path.exists(LAYOUT_JS) and os.path.samefile(path, LAYOUT_JS):
        with open(LAYOUT_JS, "w", encoding="utf-8") as f:
            f.write("// Room layout made in the map's edit mode. Written by tools/serve.py, or replace it with an exported layout.js.\n"
                    "window.LONGING_LAYOUT = null;\n")


if __name__ == "__main__":
    merge(sys.argv[1]) if len(sys.argv) > 1 else bake()
